import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent))

from config.snowflake_config import SnowflakeConfig, DEFAULT_CONFIG
from src.snowpark_dq.session_manager import SnowparkSessionManager

config = DEFAULT_CONFIG
session = SnowparkSessionManager.initialize(config)
cursor = session.cursor()

# Execute dynamic table creation in dependency order
statements = [
    # 1. Independent tables first
    """CREATE OR REPLACE DYNAMIC TABLE CURATED.DT_DIM_PARTY_CURATED
TARGET_LAG = '15 minutes'
WAREHOUSE = RCA_INGEST_WH
AS
SELECT
  PARTY_ID,
  PARTY_CODE,
  PARTY_NAME,
  PARTY_TYPE,
  ONBOARDING_DATE,
  CURRENT_DATE() AS RECORD_DATE,
  IFF(PARTY_TYPE IN ('INSTITUTIONAL', 'RETAIL'), TRUE, FALSE) AS IS_VALID_PARTY_TYPE,
  DATEDIFF(day, ONBOARDING_DATE, CURRENT_DATE()) AS DAYS_ON_BOOK
FROM RAW.DIM_PARTY_RAW
WHERE PARTY_ID IS NOT NULL""",

    # 2. Tables that depend on DT_DIM_PARTY_CURATED
    """CREATE OR REPLACE DYNAMIC TABLE CURATED.DT_DIM_ACCOUNT_CURATED
TARGET_LAG = '15 minutes'
WAREHOUSE = RCA_INGEST_WH
AS
SELECT
  a.ACCOUNT_ID,
  a.ACCOUNT_CODE,
  a.PARTY_ID,
  p.PARTY_CODE,
  p.PARTY_NAME,
  a.ACCOUNT_TYPE,
  a.ACCOUNT_OPEN_DATE,
  CURRENT_DATE() AS RECORD_DATE,
  IFF(a.ACCOUNT_TYPE IN ('BROKERAGE', 'RETIREMENT', 'MARGIN'), TRUE, FALSE) AS IS_VALID_ACCOUNT_TYPE,
  DATEDIFF(day, a.ACCOUNT_OPEN_DATE, CURRENT_DATE()) AS ACCOUNT_AGE_DAYS
FROM RAW.DIM_ACCOUNT_RAW a
LEFT JOIN CURATED.DT_DIM_PARTY_CURATED p
  ON a.PARTY_ID = p.PARTY_ID
WHERE a.ACCOUNT_ID IS NOT NULL""",

    # 3. Independent instrument table
    """CREATE OR REPLACE DYNAMIC TABLE CURATED.DT_DIM_INSTRUMENT_CURATED
TARGET_LAG = '15 minutes'
WAREHOUSE = RCA_INGEST_WH
AS
SELECT
  INSTRUMENT_ID,
  ISIN,
  RIC,
  ASSET_CLASS,
  REFERENCE_PRICE,
  CURRENT_DATE() AS RECORD_DATE,
  IFF(ASSET_CLASS IN ('EQUITY', 'BOND', 'FUND'), TRUE, FALSE) AS IS_VALID_ASSET_CLASS,
  IFF(REFERENCE_PRICE > 0, TRUE, FALSE) AS PRICE_IS_POSITIVE
FROM RAW.DIM_INSTRUMENT_RAW
WHERE INSTRUMENT_ID IS NOT NULL
  AND ISIN IS NOT NULL""",

    # 4. Fact table that depends on dimensions
    """CREATE OR REPLACE DYNAMIC TABLE CURATED.DT_FCT_TRADE_CURATED
TARGET_LAG = '15 minutes'
WAREHOUSE = RCA_INGEST_WH
AS
SELECT
  t.TRADE_ID,
  t.ACCOUNT_ID,
  t.INSTRUMENT_ID,
  t.TRADE_TS_UTC,
  t.SIDE,
  t.QUANTITY,
  t.PRICE,
  t.GROSS_AMOUNT,
  t.CURRENCY,
  a.ACCOUNT_CODE,
  a.PARTY_ID,
  i.ISIN,
  i.ASSET_CLASS,
  CURRENT_DATE() AS RECORD_DATE,
  IFF(t.ACCOUNT_ID IS NOT NULL AND a.ACCOUNT_ID IS NOT NULL, TRUE, FALSE) AS ACCOUNT_EXISTS,
  IFF(t.INSTRUMENT_ID IS NOT NULL AND i.INSTRUMENT_ID IS NOT NULL, TRUE, FALSE) AS INSTRUMENT_EXISTS,
  IFF(t.SIDE IN ('BUY', 'SELL'), TRUE, FALSE) AS VALID_SIDE,
  IFF(t.QUANTITY > 0, TRUE, FALSE) AS QUANTITY_POSITIVE,
  IFF(t.PRICE > 0, TRUE, FALSE) AS PRICE_POSITIVE,
  IFF(t.GROSS_AMOUNT > 0, TRUE, FALSE) AS AMOUNT_POSITIVE,
  HASH_AGG(t.*) OVER (PARTITION BY t.TRADE_ID) AS TRADE_HASH
FROM RAW.FCT_TRADE_RAW t
LEFT JOIN CURATED.DT_DIM_ACCOUNT_CURATED a
  ON t.ACCOUNT_ID = a.ACCOUNT_ID
LEFT JOIN CURATED.DT_DIM_INSTRUMENT_CURATED i
  ON t.INSTRUMENT_ID = i.INSTRUMENT_ID"""
]

table_names = [
    "DT_DIM_PARTY_CURATED",
    "DT_DIM_ACCOUNT_CURATED",
    "DT_DIM_INSTRUMENT_CURATED",
    "DT_FCT_TRADE_CURATED"
]

for i, (stmt, table_name) in enumerate(zip(statements, table_names)):
    try:
        print(f"Creating {table_name}...")
        cursor.execute(stmt)
        print("✅ Success")
    except Exception as e:
        print(f"❌ Error creating {table_name}: {e}")

print("Dynamic tables creation completed")

cursor.close()
session.close()