CREATE OR REPLACE WAREHOUSE RCA_INGEST_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE WAREHOUSE RCA_ANALYTICS_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE DATABASE RCA_POC_DB
  COMMENT = 'RCA Asset Data Modernisation POC';

USE DATABASE RCA_POC_DB;

CREATE OR REPLACE SCHEMA RAW;
CREATE OR REPLACE SCHEMA CURATED;
CREATE OR REPLACE SCHEMA ANALYTICS;
