USE DATABASE RCA_POC_DB;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE DIM_PARTY_RAW AS
SELECT
  SEQ4() AS PARTY_ID,
  'CLIENT_' || LPAD(SEQ4()::STRING, 8, '0') AS PARTY_CODE,
  'Client ' || SEQ4() AS PARTY_NAME,
  CASE WHEN UNIFORM(1, 100, RANDOM()) <= 60 THEN 'INSTITUTIONAL' ELSE 'RETAIL' END AS PARTY_TYPE,
  DATEADD('day', -UNIFORM(0, 3650, RANDOM()), CURRENT_DATE()) AS ONBOARDING_DATE
FROM TABLE(GENERATOR(ROWCOUNT => 10000));

CREATE OR REPLACE TABLE DIM_ACCOUNT_RAW AS
SELECT
  SEQ4() AS ACCOUNT_ID,
  'ACC_' || LPAD(SEQ4()::STRING, 10, '0') AS ACCOUNT_CODE,
  p.PARTY_ID,
  CASE WHEN UNIFORM(1, 100, RANDOM()) <= 70 THEN 'BROKERAGE'
       WHEN UNIFORM(1, 100, RANDOM()) <= 90 THEN 'RETIREMENT'
       ELSE 'MARGIN'
  END AS ACCOUNT_TYPE,
  DATEADD('day', UNIFORM(0, 365, RANDOM()), p.ONBOARDING_DATE) AS ACCOUNT_OPEN_DATE
FROM DIM_PARTY_RAW p
JOIN TABLE(GENERATOR(ROWCOUNT => 3)) g;

CREATE OR REPLACE TABLE DIM_INSTRUMENT_RAW AS
SELECT
  SEQ4() AS INSTRUMENT_ID,
  'ISIN' || LPAD(SEQ4()::STRING, 10, '0') AS ISIN,
  'RIC' || LPAD(SEQ4()::STRING, 8, '0') AS RIC,
  CASE WHEN UNIFORM(1, 100, RANDOM()) <= 60 THEN 'EQUITY'
       WHEN UNIFORM(1, 100, RANDOM()) <= 80 THEN 'BOND'
       ELSE 'FUND'
  END AS ASSET_CLASS,
  ROUND(UNIFORM(5, 500, RANDOM())::NUMBER(10, 2), 2) AS REFERENCE_PRICE
FROM TABLE(GENERATOR(ROWCOUNT => 50000));
