USE DATABASE RCA_POC_DB;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE FCT_TRADE_RAW AS
SELECT
  TRADE_ID,
  ACCOUNT_ID,
  INSTRUMENT_ID,
  TRADE_TS_UTC,
  SIDE,
  QUANTITY,
  PRICE,
  ROUND(QUANTITY * PRICE, 2) AS GROSS_AMOUNT,
  CURRENCY
FROM (
  SELECT
    SEQ4() AS TRADE_ID,
    a.ACCOUNT_ID,
    i.INSTRUMENT_ID,
    DATEADD(
      'second',
      UNIFORM(0, 365*24*3600, RANDOM()),
      DATEADD('day', -365, CURRENT_DATE())
    ) AS TRADE_TS_UTC,
    CASE WHEN UNIFORM(1, 100, RANDOM()) <= 50 THEN 'BUY' ELSE 'SELL' END AS SIDE,
    CASE WHEN UNIFORM(1, 100, RANDOM()) <= 80
         THEN UNIFORM(1, 1000, RANDOM())
         ELSE UNIFORM(1000, 100000, RANDOM())
    END AS QUANTITY,
    ROUND(
      i.REFERENCE_PRICE * (1 + NORMAL(0, 0.02, RANDOM())),
      2
    ) AS PRICE,
    'USD' AS CURRENCY
  FROM TABLE(GENERATOR(ROWCOUNT => 1000)) g
  JOIN DIM_ACCOUNT_RAW a
    ON a.ACCOUNT_ID = UNIFORM(0, (SELECT MAX(ACCOUNT_ID) FROM DIM_ACCOUNT_RAW), RANDOM())
  JOIN DIM_INSTRUMENT_RAW i
    ON i.INSTRUMENT_ID = UNIFORM(0, (SELECT MAX(INSTRUMENT_ID) FROM DIM_INSTRUMENT_RAW), RANDOM())
);

CREATE OR REPLACE TABLE FCT_TRADE_STREAM_RAW LIKE FCT_TRADE_RAW;

CREATE OR REPLACE PROCEDURE SP_GENERATE_STREAMING_TRADES(batch_size NUMBER)
RETURNS STRING
LANGUAGE SQL
AS
$$
INSERT INTO FCT_TRADE_STREAM_RAW
SELECT
  TRADE_ID,
  ACCOUNT_ID,
  INSTRUMENT_ID,
  TRADE_TS_UTC,
  SIDE,
  QUANTITY,
  PRICE,
  ROUND(QUANTITY * PRICE, 2) AS GROSS_AMOUNT,
  CURRENCY
FROM (
  SELECT
    SEQ4() AS TRADE_ID,
    a.ACCOUNT_ID,
    i.INSTRUMENT_ID,
    CURRENT_TIMESTAMP() - INTERVAL '5 minutes'
      + (ROW_NUMBER() OVER (ORDER BY SEQ4()) * INTERVAL '100 milliseconds') AS TRADE_TS_UTC,
    CASE WHEN UNIFORM(1, 100, RANDOM()) <= 50 THEN 'BUY' ELSE 'SELL' END AS SIDE,
    CASE WHEN UNIFORM(1, 100, RANDOM()) <= 80
         THEN UNIFORM(1, 1000, RANDOM())
         ELSE UNIFORM(1000, 100000, RANDOM())
    END AS QUANTITY,
    ROUND(
      i.REFERENCE_PRICE * (1 + NORMAL(0, 0.02, RANDOM())),
      2
    ) AS PRICE,
    'USD' AS CURRENCY
  FROM TABLE(GENERATOR(ROWCOUNT => :batch_size)) g
  JOIN DIM_ACCOUNT_RAW a
    ON a.ACCOUNT_ID = UNIFORM(0, (SELECT MAX(ACCOUNT_ID) FROM DIM_ACCOUNT_RAW), RANDOM())
  JOIN DIM_INSTRUMENT_RAW i
    ON i.INSTRUMENT_ID = UNIFORM(0, (SELECT MAX(INSTRUMENT_ID) FROM DIM_INSTRUMENT_RAW), RANDOM())
);

SELECT 'Inserted ' || :batch_size || ' streaming trades';
$$;

CREATE OR REPLACE TASK TASK_GENERATE_STREAMING_TRADES
  WAREHOUSE = RCA_INGEST_WH
  SCHEDULE = 'USING CRON * * * * * UTC'
AS
CALL SP_GENERATE_STREAMING_TRADES(1000);

ALTER TASK TASK_GENERATE_STREAMING_TRADES RESUME;
