USE DATABASE RCA_POC_DB;
USE SCHEMA CURATED;

-- Curated dimensions
CREATE OR REPLACE TABLE DIM_PARTY AS
SELECT
  PARTY_ID,
  PARTY_CODE,
  PARTY_NAME,
  PARTY_TYPE,
  ONBOARDING_DATE
FROM RAW.DIM_PARTY_RAW;

CREATE OR REPLACE TABLE DIM_ACCOUNT AS
SELECT
  ACCOUNT_ID,
  ACCOUNT_CODE,
  PARTY_ID,
  ACCOUNT_TYPE,
  ACCOUNT_OPEN_DATE
FROM RAW.DIM_ACCOUNT_RAW;

CREATE OR REPLACE TABLE DIM_INSTRUMENT AS
SELECT
  INSTRUMENT_ID,
  ISIN,
  RIC,
  ASSET_CLASS,
  REFERENCE_PRICE
FROM RAW.DIM_INSTRUMENT_RAW;

-- Curated trade fact (history + streaming)
CREATE OR REPLACE TABLE FCT_TRADE AS
SELECT * FROM RAW.FCT_TRADE_RAW
UNION ALL
SELECT * FROM RAW.FCT_TRADE_STREAM_RAW;
