USE DATABASE RCA_POC_DB;
USE SCHEMA ANALYTICS;

-- Simple recent activity views for demos

CREATE OR REPLACE VIEW VW_RECENT_TRADE_ACTIVITY AS
SELECT
  t.TRADE_TS_UTC,
  t.SIDE,
  t.QUANTITY,
  t.PRICE,
  t.GROSS_AMOUNT,
  a.ACCOUNT_CODE,
  p.PARTY_CODE,
  p.PARTY_TYPE,
  i.ASSET_CLASS
FROM CURATED.FCT_TRADE t
JOIN CURATED.DIM_ACCOUNT a ON t.ACCOUNT_ID = a.ACCOUNT_ID
JOIN CURATED.DIM_PARTY p ON a.PARTY_ID = p.PARTY_ID
JOIN CURATED.DIM_INSTRUMENT i ON t.INSTRUMENT_ID = i.INSTRUMENT_ID
WHERE t.TRADE_TS_UTC >= DATEADD('hour', -1, CURRENT_TIMESTAMP());

CREATE OR REPLACE VIEW VW_TOP_ACCOUNTS_BY_VOLUME_LAST_1H AS
SELECT
  a.ACCOUNT_CODE,
  p.PARTY_CODE,
  SUM(t.GROSS_AMOUNT) AS TOTAL_TURNOVER_USD,
  COUNT(*) AS TRADE_COUNT
FROM CURATED.FCT_TRADE t
JOIN CURATED.DIM_ACCOUNT a ON t.ACCOUNT_ID = a.ACCOUNT_ID
JOIN CURATED.DIM_PARTY p ON a.PARTY_ID = p.PARTY_ID
WHERE t.TRADE_TS_UTC >= DATEADD('hour', -1, CURRENT_TIMESTAMP())
GROUP BY a.ACCOUNT_CODE, p.PARTY_CODE
ORDER BY TOTAL_TURNOVER_USD DESC
LIMIT 50;

CREATE OR REPLACE VIEW VW_VOLUME_BY_ASSET_CLASS_LAST_1H AS
SELECT
  i.ASSET_CLASS,
  SUM(t.GROSS_AMOUNT) AS TOTAL_TURNOVER_USD,
  COUNT(*) AS TRADE_COUNT
FROM CURATED.FCT_TRADE t
JOIN CURATED.DIM_INSTRUMENT i ON t.INSTRUMENT_ID = i.INSTRUMENT_ID
WHERE t.TRADE_TS_UTC >= DATEADD('hour', -1, CURRENT_TIMESTAMP())
GROUP BY i.ASSET_CLASS
ORDER BY TOTAL_TURNOVER_USD DESC;
