-- =====================================================
-- Dynamic Tables for Asset Data Transformation
-- =====================================================
-- Dynamic Tables provide declarative transformations 
-- with automatic refresh dependency handling

USE DATABASE RCA_POC_DB;
USE SCHEMA CURATED;

-- =====================================================
-- CURATED LAYER - Conformed Asset Dimensions
-- =====================================================

CREATE OR REPLACE DYNAMIC TABLE DT_DIM_PARTY_CURATED
TARGET_LAG = '15 minutes'
WAREHOUSE = RCA_INGEST_WH
AS
SELECT
  PARTY_ID,
  PARTY_CODE,
  PARTY_NAME,
  PARTY_TYPE,
  ONBOARDING_DATE,
  CURRENT_DATE() AS RECORD_DATE,
  IFF(PARTY_TYPE IN ('INSTITUTIONAL', 'RETAIL'), TRUE, FALSE) AS IS_VALID_PARTY_TYPE,
  DATEDIFF(day, ONBOARDING_DATE, CURRENT_DATE()) AS DAYS_ON_BOOK
FROM RAW.DIM_PARTY_RAW
WHERE PARTY_ID IS NOT NULL;

COMMENT ON DYNAMIC TABLE DT_DIM_PARTY_CURATED IS 'Curated party dimension with data quality enrichment';

-- Account Dimension with business logic
CREATE OR REPLACE DYNAMIC TABLE DT_DIM_ACCOUNT_CURATED
TARGET_LAG = '15 minutes'
WAREHOUSE = RCA_INGEST_WH
AS
SELECT
  a.ACCOUNT_ID,
  a.ACCOUNT_CODE,
  a.PARTY_ID,
  p.PARTY_CODE,
  p.PARTY_NAME,
  a.ACCOUNT_TYPE,
  a.ACCOUNT_OPEN_DATE,
  CURRENT_DATE() AS RECORD_DATE,
  IFF(a.ACCOUNT_TYPE IN ('BROKERAGE', 'RETIREMENT', 'MARGIN'), TRUE, FALSE) AS IS_VALID_ACCOUNT_TYPE,
  DATEDIFF(day, a.ACCOUNT_OPEN_DATE, CURRENT_DATE()) AS ACCOUNT_AGE_DAYS
FROM RAW.DIM_ACCOUNT_RAW a
LEFT JOIN DT_DIM_PARTY_CURATED p
  ON a.PARTY_ID = p.PARTY_ID
WHERE a.ACCOUNT_ID IS NOT NULL;

COMMENT ON DYNAMIC TABLE DT_DIM_ACCOUNT_CURATED IS 'Curated account dimension with party reference';

-- Instrument Dimension
CREATE OR REPLACE DYNAMIC TABLE DT_DIM_INSTRUMENT_CURATED
TARGET_LAG = '15 minutes'
WAREHOUSE = RCA_INGEST_WH
AS
SELECT
  INSTRUMENT_ID,
  ISIN,
  RIC,
  ASSET_CLASS,
  REFERENCE_PRICE,
  CURRENT_DATE() AS RECORD_DATE,
  IFF(ASSET_CLASS IN ('EQUITY', 'BOND', 'FUND'), TRUE, FALSE) AS IS_VALID_ASSET_CLASS,
  IFF(REFERENCE_PRICE > 0, TRUE, FALSE) AS PRICE_IS_POSITIVE
FROM RAW.DIM_INSTRUMENT_RAW
WHERE INSTRUMENT_ID IS NOT NULL
  AND ISIN IS NOT NULL;

COMMENT ON DYNAMIC TABLE DT_DIM_INSTRUMENT_CURATED IS 'Curated instrument dimension with validation flags';

-- =====================================================
-- CURATED LAYER - Fact Tables
-- =====================================================

CREATE OR REPLACE DYNAMIC TABLE DT_FCT_TRADE_CURATED
TARGET_LAG = '15 minutes'  -- More frequent refresh for fact tables
WAREHOUSE = RCA_INGEST_WH
AS
SELECT
  t.TRADE_ID,
  t.ACCOUNT_ID,
  t.INSTRUMENT_ID,
  t.TRADE_TS_UTC,
  t.SIDE,
  t.QUANTITY,
  t.PRICE,
  t.GROSS_AMOUNT,
  t.CURRENCY,
  a.ACCOUNT_CODE,
  a.PARTY_ID,
  i.ISIN,
  i.ASSET_CLASS,
  CURRENT_DATE() AS RECORD_DATE,
  -- Data quality flags
  IFF(t.ACCOUNT_ID IS NOT NULL AND a.ACCOUNT_ID IS NOT NULL, TRUE, FALSE) AS ACCOUNT_EXISTS,
  IFF(t.INSTRUMENT_ID IS NOT NULL AND i.INSTRUMENT_ID IS NOT NULL, TRUE, FALSE) AS INSTRUMENT_EXISTS,
  IFF(t.SIDE IN ('BUY', 'SELL'), TRUE, FALSE) AS VALID_SIDE,
  IFF(t.QUANTITY > 0, TRUE, FALSE) AS QUANTITY_POSITIVE,
  IFF(t.PRICE > 0, TRUE, FALSE) AS PRICE_POSITIVE,
  IFF(t.GROSS_AMOUNT > 0, TRUE, FALSE) AS AMOUNT_POSITIVE,
  HASH_AGG(t.*) OVER (PARTITION BY t.TRADE_ID) AS TRADE_HASH
FROM RAW.FCT_TRADE_RAW t
LEFT JOIN DT_DIM_ACCOUNT_CURATED a
  ON t.ACCOUNT_ID = a.ACCOUNT_ID
LEFT JOIN DT_DIM_INSTRUMENT_CURATED i
  ON t.INSTRUMENT_ID = i.INSTRUMENT_ID;

COMMENT ON DYNAMIC TABLE DT_FCT_TRADE_CURATED IS 'Curated trade fact table with referential integrity checks';

-- =====================================================
-- ANALYTICS LAYER - Aggregated Views
-- =====================================================

CREATE OR REPLACE DYNAMIC TABLE DT_TRADE_DAILY_SUMMARY
TARGET_LAG = '1 hour'
WAREHOUSE = RCA_ANALYTICS_WH
AS
SELECT
  DATE(TRADE_TS_UTC) AS TRADE_DATE,
  ASSET_CLASS,
  SIDE,
  COUNT(DISTINCT TRADE_ID) AS TRADE_COUNT,
  SUM(QUANTITY) AS TOTAL_QUANTITY,
  SUM(GROSS_AMOUNT) AS TOTAL_AMOUNT,
  AVG(PRICE) AS AVG_PRICE,
  MIN(PRICE) AS MIN_PRICE,
  MAX(PRICE) AS MAX_PRICE,
  COUNT(DISTINCT PARTY_ID) AS UNIQUE_PARTIES,
  COUNT(DISTINCT ACCOUNT_ID) AS UNIQUE_ACCOUNTS,
  CURRENT_TIMESTAMP() AS CALCULATED_AT
FROM DT_FCT_TRADE_CURATED
WHERE ACCOUNT_EXISTS = TRUE 
  AND INSTRUMENT_EXISTS = TRUE
  AND VALID_SIDE = TRUE
GROUP BY 
  DATE(TRADE_TS_UTC),
  ASSET_CLASS,
  SIDE;

COMMENT ON DYNAMIC TABLE DT_TRADE_DAILY_SUMMARY IS 'Daily trade analytics summary';

-- Account-level analytics
CREATE OR REPLACE DYNAMIC TABLE DT_ACCOUNT_ANALYTICS
TARGET_LAG = '1 hour'
WAREHOUSE = RCA_ANALYTICS_WH
AS
SELECT
  a.ACCOUNT_ID,
  a.ACCOUNT_CODE,
  a.PARTY_ID,
  p.PARTY_NAME,
  a.ACCOUNT_TYPE,
  COUNT(DISTINCT t.TRADE_ID) AS TRADE_COUNT,
  SUM(CASE WHEN t.SIDE = 'BUY' THEN t.GROSS_AMOUNT ELSE 0 END) AS BUY_AMOUNT,
  SUM(CASE WHEN t.SIDE = 'SELL' THEN t.GROSS_AMOUNT ELSE 0 END) AS SELL_AMOUNT,
  SUM(t.GROSS_AMOUNT) AS TOTAL_AMOUNT,
  MAX(t.TRADE_TS_UTC) AS LAST_TRADE_DATE,
  COUNT(DISTINCT CASE WHEN t.ACCOUNT_EXISTS THEN 1 END) AS VALID_TRADES,
  COUNT(DISTINCT CASE WHEN NOT t.ACCOUNT_EXISTS THEN 1 END) AS ORPHANED_TRADES,
  CURRENT_TIMESTAMP() AS CALCULATED_AT
FROM DT_DIM_ACCOUNT_CURATED a
LEFT JOIN DT_DIM_PARTY_CURATED p
  ON a.PARTY_ID = p.PARTY_ID
LEFT JOIN DT_FCT_TRADE_CURATED t
  ON a.ACCOUNT_ID = t.ACCOUNT_ID
GROUP BY
  a.ACCOUNT_ID,
  a.ACCOUNT_CODE,
  a.PARTY_ID,
  p.PARTY_NAME,
  a.ACCOUNT_TYPE;

COMMENT ON DYNAMIC TABLE DT_ACCOUNT_ANALYTICS IS 'Account-level analytics with data quality indicators';
